### ISSUE TITLE
Exit code equal to 0 on error

### ISSUE THREAD

**Issue by martinos** [cldwalker/boson#12]
Normally when we run a ruby script and an exception is not caught, the exit code is set to 1. 

With boson the exit code is equals to 0. This prevents us to make shells scripts that take a different action on failure. 

Is there a way to set the exit code to 1 on uncaught exception.

**Comment by cldwalker** [comment]
Closed by af4bb240ad70fc56ff8040fbfe06cda6f9ee60a1: Boson commands on the commandline exit properly with 1

**Comment by cldwalker** [comment]
Done: af4bb240ad70fc56ff8040fbfe06cda6f9ee60a1

Thanks for the reminder. It was on my todo list. :)

**Comment by martinos** [comment]
Thanks you very much, your work is much appreciated.
