### ISSUE TITLE
Install on 1.9.2.rc2

### ISSUE THREAD

**Issue by ticktricktrack** [cldwalker/boson#14]
What I did:
gem install boson
require "boson"
Boson start

What happened:

<code>
Unable to load library Boson::Commands::Core. Reason: can't add a new key into hash during iteration
  /Users/rainerkuhn/.rvm/gems/ruby-1.9.2-rc2/gems/boson-0.2.5/lib/boson/manager.rb:148:in `[]='
  /Users/rainerkuhn/.rvm/gems/ruby-1.9.2-rc2/gems/boson-0.2.5/lib/boson/manager.rb:148:in`block (2 levels) in create_class_aliases'
  /Users/rainerkuhn/.rvm/gems/ruby-1.9.2-rc2/gems/boson-0.2.5/lib/boson/manager.rb:148:in `each'
Unable to load library Boson::Commands::WebCore. Reason: can't add a new key into hash during iteration
  /Users/rainerkuhn/.rvm/gems/ruby-1.9.2-rc2/gems/boson-0.2.5/lib/boson/manager.rb:148:in`[]='
  /Users/rainerkuhn/.rvm/gems/ruby-1.9.2-rc2/gems/boson-0.2.5/lib/boson/manager.rb:148:in `block (2 levels) in create_class_aliases'
  /Users/rainerkuhn/.rvm/gems/ruby-1.9.2-rc2/gems/boson-0.2.5/lib/boson/manager.rb:148:in`each'
</code>

Same error from Bash.

Ray

**Comment by cldwalker** [comment]
I'll take a look at this when I can get rvm to install 1.9.2-rc2 correctly. Fyi, on a 1.9.2-preview1 mac osx, boson passes all tests.

**Comment by cldwalker** [comment]
Fix 1.9.2 can't add a new key into hash during iteration; closed by 265a56b8628dfee82716b359843a2b7f8fab36ca

**Comment by cldwalker** [comment]
Latest boson should be working on 1.9.2-rc2
