### ISSUE TITLE
Warning when using boson on cron job

### ISSUE THREAD

**Issue by martinos** [cldwalker/boson#15]
When I run a boson task on a cron job I get the following message.

tput: No value for $TERM and no -T specified

Is it possible to remove this warning? In my case I forces crontab to send me an email.

**Comment by cldwalker** [comment]
As far as I know there aren't any tput calls in boson. There is [one in hirb though](http://github.com/cldwalker/hirb/blob/master/lib/hirb/util.rb#L64). If I have time this weekend, I'll check this out.

**Comment by martinos** [comment]
You are right its my mistake.

**Comment by cldwalker** [comment]
Fixed and pushed: http://github.com/cldwalker/hirb/commit/42a5f5a5f372f4e7d74a0865e611fbec7779d201
