### ISSUE TITLE
tests under rubinius-1.1.1/1.2.0

### ISSUE THREAD

**Issue by zhando** [cldwalker/boson#20]
As discussed on ruby.cmd.line, includes the 12 errors connected with argument_inspector and 3 other issues.

https://gist.github.com/728503

Run under 64-bit Linux - Ubuntu 10.10 if that helps. Again the issue with argument_inspector is that rubinius does not support set_trace_func so the twelve tests that end up using scrape_with_eval return errors.

As a substitute, you can scrape method parameters with method#parameters but this works only under mri 1.9 and the current stable rubinius. I don't know of any substitute for scraping the default values of parameters.

**Comment by cldwalker** [comment]
As I've mentioned elsewhere, I would love to have boson running on every ruby.
Realistically, it will only get addressed when it bites me.

I encourage anyone who's interested in this to look at lib/boson/inspectors/argument_inspector.rb and submit pull requests.

**Comment by zhando** [comment]
The rbx-tracer library for rubinius has been released which simulates set_trace_func. I installed it under rbx-1.2.0, required it in boson's test_helper.rb and ran the tests. It cleans them up a bit:

https://gist.github.com/760117

Now the tests merely fail instead of generating 12 errors but it's some progress. rbx-tracer is a young library and it looks like it doesn't yet support the call event.

**Comment by cldwalker** [comment]
I'm closing this as boson 0.5 will be smaller. If it still doesn't work on rbx, then we can address in a separate issue ;)

**Comment by zhando** [comment]
https://gist.github.com/1673645

I really need to do some more testing but I'll try to post my branch this evening. This has been kind of fun.. Learned a ton on this one.

In addition to rbx 1.2.4 the test also passes on 1.8.7, latest ree, 1.9.2, 1.9.3 and even jruby-head but it wags its finger at something I'm doing.

Can't compile 1.9.1 for some reason but probably shouldn't bother. 1.8.6? no chance..
