### ISSUE TITLE
Loading Boson after Hirb results in errors

### ISSUE THREAD

**Issue by allanclloyds** [cldwalker/boson#21]
I couldn't see this documented anywhere, so just in case anyone else hits the same problem: you need to load Boson before Hirb otherwise you get the following error.

```
ruby-1.9.2-p0 > require 'boson'
 => true
ruby-1.9.2-p0 > Boson.start
The following commands conflict with existing commands: menu. Attempting load into the namespace core...
Error: No method exists to redefine command 'usage'.
Error: No method exists to redefine command 'commands'.
Error: No method exists to redefine command 'libraries'.
Error: No method exists to redefine command 'load_library'.
Loaded library core
Loaded library web_core
 => nil
```

**Comment by cldwalker** [comment]
To be more specific, if you `require 'hirb'; extend Hirb::Console` before requiring boson, then you'll see the expected conflict message. However, the messages "Error: No method exists to redefine command 'X'." are unexpected and need to be fixed.

**Comment by cldwalker** [comment]
This will no longer be an issue in boson 0.5 as hirb won't be a dependency and it's integration will be changed and moved to boson-all
