### ISSUE TITLE
boson install URL does not work

### ISSUE THREAD

**Issue by sanemat** [cldwalker/boson#22]
I try http://tagaholic.me/2009/10/14/boson-command-your-ruby-universe.html, but it does not work.
    $ boson install https://gist.github.com/raw/203861/c063260bef7f004c9db4c2a7719ff649b59d3ade/git-authors -m
    Error: Unable to fetch url

I tried vorbose mode.
    $ boson -v install https://gist.github.com/raw/203861/c063260bef7f004c9db4c2a7719ff649b59d3ade/git-authors -m
https://gist.github.com/792310

```
my environment
$ boson --version
boson 0.3.2
$ ruby --version
ruby 1.9.2p136 (2010-12-25 revision 30365) [x86_64-linux]
```

**Comment by cldwalker** [comment]
Thanks for the bug report. I'll look into this later in the week.

**Comment by cldwalker** [comment]
fix https install, closed by 20607d273bd802f86ef1b3209b4b213930106984

**Comment by cldwalker** [comment]
Nice bug. It was affecting all ruby versions

**Comment by cldwalker** [comment]
Just released with this fix
