### ISSUE TITLE
Not able to use pipe commands

### ISSUE THREAD

**Issue by martinos** [cldwalker/boson#23]
I tried the example for piping the result of a command into the browser pipe and it did't work. Maybe I am doing something wrong.

Here is the what I added into my boson.yml file:

<pre><code>:pipe_options:
  :browser:
    :type: :boolean
    :desc: Open in browser
<./code></pre>

when I type in the bash:
<pre><code>boson my_command --browser
</pre></code>
I get the flowing error:
<pre><code>'my_command' was called incorrectly.
</pre></code>
Have I done something wrong ?

**Comment by cldwalker** [comment]
The config looks good. To verify that your command has --browser a global pipe option, run `boson my_command -hv`. You should see --browser listed under global options. What does `boson -v my_command --browser` give you? Also ruby version + platform is helpful.

**Comment by martinos** [comment]
<pre><code>boson my_command -hv</code></pre>

returns:

<pre><code>'my_command' was called incorrectly.
my_command 
</code></pre>

If I call:

<pre><code>boson my_command</code></pre>

I get:

<pre><code>http://www.google.com
</code></pre>

What are the -hv options? Are they global options?

When I type:

<pre><code>boson -v my_command --browser</code></pre>

I get:

<pre><code>Loaded library core
Loaded library web_core
No libraries indexed
Loaded library remote_cp
'my_command' was called incorrectly.
my_command 
Original error: wrong number of arguments (1 for 0)
  /Users/martinos/.rvm/gems/ruby-1.8.7-p302/gems/boson-0.3.2/lib/boson.rb:87:in `my_command'
  /Users/martinos/.rvm/gems/ruby-1.8.7-p302/gems/boson-0.3.2/lib/boson.rb:87:in `send'
  /Users/martinos/.rvm/gems/ruby-1.8.7-p302/gems/boson-0.3.2/lib/boson.rb:87:in `full_invoke'
  /Users/martinos/.rvm/gems/ruby-1.8.7-p302/gems/boson-0.3.2/lib/boson/runners/bin_runner.rb:157:in `execute_command'
  /Users/martinos/.rvm/gems/ruby-1.8.7-p302/gems/boson-0.3.2/lib/boson/scientist.rb:47:in `inject'
  /Users/martinos/.rvm/gems/ruby-1.8.7-p302/gems/boson-0.3.2/lib/boson/runners/bin_runner.rb:152:in `each'
  /Users/martinos/.rvm/gems/ruby-1.8.7-p302/gems/boson-0.3.2/lib/boson/runners/bin_runner.rb:152:in `inject'
  /Users/martinos/.rvm/gems/ruby-1.8.7-p302/gems/boson-0.3.2/lib/boson/runners/bin_runner.rb:152:in `execute_command'
  /Users/martinos/.rvm/gems/ruby-1.8.7-p302/gems/boson-0.3.2/lib/boson/runners/bin_runner.rb:79:in `start'
  /Users/martinos/.rvm/gems/ruby-1.8.7-p302/gems/boson-0.3.2/bin/boson:6
  /Users/martinos/.rvm/gems/ruby-1.8.7-p302/bin/boson:19:in `load'
  /Users/martinos/.rvm/gems/ruby-1.8.7-p302/bin/boson:19
</code></pre>

My ruby version is ruby-1.8.7-p302 and I am on OS X 10.5.8.

**Comment by cldwalker** [comment]
Yep. they're global options, help and verbose. They should work after a command. What does `boson -hv my_command` or `boson -h -v my_command` give you?

**Comment by martinos** [comment]
I when I run:<pre><code>boson -hv my_command
</code></pre>I get: <pre><code>Loaded library core
Loaded library web_core
No libraries indexed
No libraries indexed
Loaded library remote_cp
my_command</code></pre>
RemoteCp is the module where my my_command is located.

**Comment by cldwalker** [comment]
So you won't get global options on any command unless you call render_options, options or config :option_command => true before it. For your command this works:

```
# @render_options :render => true
def my_command
  "http://www.google.com"
end
```

The :render option is to turn off automated hirb rendering which is needed since you don't want your string to be rendered by hirb. For [all my browser libraries](https://github.com/cldwalker/irbfiles/tree/master/boson/commands/public/url), I don't explicitly set the above options. Instead I have [a boson plugin](https://github.com/cldwalker/irbfiles/blob/master/boson/commands/exp/plugins/url_libraries.rb) which adds these default options for any libraries under url/.

Let me know if the above works.

**Comment by martinos** [comment]
Thank you very much, it works.

**Comment by cldwalker** [comment]
cool
