### ISSUE TITLE
Feature: RVM support

### ISSUE THREAD

**Issue by hedgehog** [cldwalker/boson#24]
Would be useful to have RVM support.
In addition to the global repo `/etc/bin` have `bin/boson` which takes precedence over `/etc/boson` in case of duplicates.

RVM Example Path:
    $ which boson
     /home/hedge/.rvm/gems/ruby-1.9.2-p136@bbb-bdd-meta-bdd/bin/boson

So perhaps have boson recognize as a global repository:
    /home/hedge/.rvm/gems/ruby-1.9.2-p136@bbb-bdd-meta-bdd/bin/.boson/commands

**Comment by cldwalker** [comment]
A gem doesn't handle what directory it's executable is installed in. That's up to rubygems and the user's own manipulation of $PATH.

As for adding command repositories in a bin directory, not appealing. I wouldn't want any gem to be looking in my bin directories for non-executables. Bin directories should only contain executables.

**Comment by hedgehog** [comment]
Ack.  I only saw your [gist](https://gist.github.com/265007) after posting those issues. Apologies.
