### ISSUE TITLE
Access a project's MyModules from the project myexec executable/command line

### ISSUE THREAD

**Issue by hedgehog** [cldwalker/boson#25]
Would be useful to be able to create a custom binary in a project, such that the following
just works.

```
$ cat bin/myexec
#!/usr/bin/env ruby
require 'boson'
require 'boson/runners/bin_runner'

load_library ::Math, :commands=>%w{sin cos tan}
Boson::BinRunner.start 
```

Unless there is a way to do this.  Note I don't want to have to customize local or global repos, just use my modules by inserting a require and then loading the module name.

Is implementing this possible?

In the mean time: Is there a way to achieve this result?

**Comment by cldwalker** [comment]
Such a module could be possible if it had a Boson module included into it _before_ methods (commands) are defined:

```
 module MyCommands
   include Boson::BinLibrary
   # Some description
   def command(arg1, options={})
   end
 end
```

I don't have a need for this but when I do I'll write it. Patches welcome in the meantime :)

**Comment by hedgehog** [comment]
I only saw the suggested approach to this after opening the issue, so in case anyone else would like to use boson right now:
The current approach is set out in [this gist](https://gist.github.com/265007), which arose i the course of issue #3.
This might also give some insight into what is required.
Also AFAICT the `extend self` is not required, at least if you use `module_function` in your module, e.g. `MyCommands` above.

**Comment by cldwalker** [comment]
boson 0.5 will address something similar to this. Allowing for executables that have custom commands:

class MyRunner < Boson::Runner
   def command1
   end

   def command2
   end
end

We can revisit this in a separate issue if still interested and 0.5 doesn't help
