### ISSUE TITLE
Boson::Manager.load <Module>: Ignores description in <Module> 

### ISSUE THREAD

**Issue by hedgehog** [cldwalker/boson#26]
Example:
https://gist.github.com/265007

The descriptions are not printed if you invoke:
    $./run_example.rb commands

**Comment by cldwalker** [comment]
Again, expected behavior. :desc option with description needs to be passed explicitly to lines 23-24. If you want all the automated usage and desc goodness of boson, you need to follow it's conventions i.e. modules go in ~/.boson/commands/
