### ISSUE TITLE
Reading options from file no longer working?

### ISSUE THREAD

**Issue by michaelbarton** [cldwalker/boson#32]
Hi,

I created my own boson command a while ago - https://github.com/michaelbarton/pubmed-boson. I've found recently that the default options for my command are no longer being read from my ~/.irbfiles/boson/config/boson.yml file. Has something changed recently in boson?

Here is my options file - 
  https://github.com/michaelbarton/irbfiles/blob/master/boson/config/boson.yml

Mike

**Comment by cldwalker** [comment]
What's the last version that worked for you? The latest release 0.4.0 has some changes that may be causing this. 0.3.4 work?

**Comment by cldwalker** [comment]
Seeing as you only have one command and the new boson is out, it may make sense to make an executable out of your library i.e. bin/pubmed:

``` ruby
#!/usr/bin/env ruby
require 'boson/runner'
class PubMed < Boson::Runner
  options
  config
  def query
  # ...
  end
end
```

**Comment by cldwalker** [comment]
Since I haven't heard back, I'm assuming this worked out. Ping this ticket if you need help and I can reopen.
