### ISSUE TITLE
How do you bootstrap boson?

### ISSUE THREAD

**Issue by rsanheim** [cldwalker/boson#33]
Include instructions for other devs on how to get things setup for boson.  What is the minimum stuff needed with rip or whatever else to get running?

**Comment by cldwalker** [comment]
I think you're looking for http://tagaholic.me/contributing.html .
There's a link to it at the end of the readme. I leave it up to the
dev to use bundler, rvm, rbenv or plain gem as far as how they want to
install gem deps. Any of them allow you to setup and run tests

On Tue, Mar 20, 2012 at 10:16 AM, Rob Sanheim
reply@reply.github.com
wrote:

**Comment by rsanheim** [comment]
Ah okay -- any reason you don't just go with gemspec + bundler, which seems to be the standard that most gems are going now?

**Comment by cldwalker** [comment]
bundler is overkill for any gem development I've ever done so I keep it simple with rip or rbenv. I'm a fan of letting users decide how they want to develop a gem with a local .gitignore. Maybe when I've found a way to keep a consistent .gitignore across projects I'll add a sane default.

**Comment by cldwalker** [comment]
Closing. If there's more here, please discuss and I can reopen.
