### ISSUE TITLE
Have error during installation

### ISSUE THREAD

**Issue by HoangUong** [cldwalker/boson#37]
Hi,
I have ruby 1.9.3 on Windows Vista.
I have errors:
1.  During installation
2.  When executing an example
The errors are shown below.

Thanks,
Hoang

C:>ruby -v
ruby 1.9.3p125 (2012-02-16) [i386-mingw32]

C:>gem install boson
Fetching: boson-1.2.3.gem (100%)
Successfully installed boson-1.2.3
1 gem installed
Installing ri documentation for boson-1.2.3...
ERROR:  While generating documentation for boson-1.2.3
... MESSAGE:   Invalid argument - ./Boson/Runner/:
... RDOC args: --ri --op C:/hoang/app/Ruby193/lib/ruby/gems/1.9.1/doc/boson-1.2.
3/ri lib README.md LICENSE.txt Upgrading.md --title boson-1.2.3 Documentation --
quiet

irb(main):001:0> require 'boson/runner'
=> true
irb(main):002:0>
irb(main):003:0\* class CowRunner < Boson::Runner
irb(main):004:1>   option :urgent, type: :boolean
irb(main):005:1>   def say(text, options={})
irb(main):006:2>     text.capitalize! if options[:urgent]
irb(main):007:2>     puts text
irb(main):008:2>   end
irb(main):009:1>
irb(main):010:1\*   def moo
irb(main):011:2>     puts "MOOOO"
irb(main):012:2>   end
irb(main):013:1> end
=> nil
irb(main):014:0>
irb(main):015:0\* CowRunner.start
Usage: irb [OPTIONS] COMMAND [ARGS]

Available commands:
  moo
  say

Options:
  -h, --help  Displays this help message
=> nil
irb(main):016:0> cow moo
MOOOO
NoMethodError: undefined method `cow' for main:Object
        from (irb):16
        from C:/.../app/Ruby193/bin/irb:12:in`<main>'
irb(main):017:0>

**Comment by cldwalker** [comment]
It seems you're trying the example incorrectly. Everything from the 'class CowRunner' to 'CowRunner.start' should be in a file i.e bin/cow. You should then invoke the file with arguments from a shell i.e. `bin/cow moo`

**Comment by HoangUong** [comment]
You are right. Thanks for the explanation. It works fine.
-Hoang

**Comment by cldwalker** [comment]
Great! Glad it worked
