### ISSUE TITLE
running boson commands faled_libraries= undefined method

### ISSUE THREAD

**Issue by makrisoft** [cldwalker/boson#41]
ruby -v
ruby 1.9.3p125 (2012-02-16 revision 34643) [x86_64-linux]

boson commands
Error: undefined method `failed_libraries=' for Boson::Manager:Class

Any help would be much appreciated

**Comment by cldwalker** [comment]
Are you using boson-more? If so, could I see your full setup? I'll also need the full stacktrace for your error - `boson -b commands`

**Comment by makrisoft** [comment]
Hi,

I have boson-more installed as well. I'm trying to use it on both jruby and mri. Here is the info:

rvm rubies

   jruby-1.6.7 [ amd64 ]
=\* ruby-1.9.3-p125 [ x86_64 ]

and here is the stack:

emakris@frodo:~$ boson -b commands
Error: undefined method `failed_libraries=' for Boson::Manager:Class
Original error: undefined method`failed_libraries=' for Boson::Manager:Class
  /home/emakris/.rvm/gems/ruby-1.9.3-p125/gems/boson-1.2.3/lib/boson/repo_index.rb:24:in `update'
  /home/emakris/.rvm/gems/ruby-1.9.3-p125/gems/boson-more-0.2.2/lib/boson/index.rb:13:in`block in update'
  /home/emakris/.rvm/gems/ruby-1.9.3-p125/gems/boson-more-0.2.2/lib/boson/index.rb:13:in `each'
  /home/emakris/.rvm/gems/ruby-1.9.3-p125/gems/boson-more-0.2.2/lib/boson/index.rb:13:in`update'
  /home/emakris/.rvm/gems/ruby-1.9.3-p125/gems/boson-more-0.2.2/lib/boson/runner_options.rb:22:in `init'
  /home/emakris/.rvm/gems/ruby-1.9.3-p125/gems/boson-1.2.3/lib/boson/bin_runner.rb:101:in`start'
  /home/emakris/.rvm/gems/ruby-1.9.3-p125/gems/boson-1.2.3/bin/boson:6:in `<top (required)>'
  /home/emakris/.rvm/gems/ruby-1.9.3-p125/bin/boson:19:in`load'
  /home/emakris/.rvm/gems/ruby-1.9.3-p125/bin/boson:19:in `<main>'

**Comment by cldwalker** [comment]
I've released 1.2.4 to fix this

**Comment by makrisoft** [comment]
thanks for the prompt fix!!!
