### ISSUE TITLE
guide to per-project usage

### ISSUE THREAD

**Issue by leemhenson** [cldwalker/boson#44]
Hi

I'm using Boson as a Rake replacement, because it seems very lightweight with much better options parsing. I preferred the look of it to Thor as well. Unfortunately I've got myself a bit stuck, and I get the feeling I'm missing something hidden in plain sight. 

I've got a single my_boson script file in the root of my project:

```
#!/usr/bin/env ruby

require 'rubygems'
require 'boson/runner'

class MyRunner < Boson::Runner
  desc "blah blah"
  def task1
    # ...
  end

  desc "blah blah"
  def task2
    # ...
  end

  # etc etc
end


MyRunner.start
```

This works fine, but it's becoming somewhat unwieldy as the number of tasks increases. What's the right way to decompose this file so that I have related tasks grouped together in separate files? I've read the docs and the code, particularly around libraries, but I can't see an obvious this-is-the-way-to-do-it hook. Ideally I'd like to namespace my commands a bit too, e.g.

./my_boson mongodb drop_databases
./my_boson mongodb rebuild_indexes
etc.

Guidance appreciated!

**Comment by cldwalker** [comment]
If you don't care about namespacing, then you can always find a way to break a class into multiple files i.e.:

```
lib/
  my_gem/
    runner.rb - requires my_gem/runner/mongodb.rb ...
    runner/
      mongodb.rb
      couchdb.rb
      otherdb.rb
```

If you really want namespaces/subcommands for a runner, I'm sorry to say that boson doesn't have it and recommend thor for this. If you use the boson executable directly it does have support for namespaces via https://github.com/cldwalker/boson-more i.e. `boson namespace.command`.

**Comment by leemhenson** [comment]
That's ok, I'm going to give Thor a go to see if that's maybe a better fit. Thanks anyway!
