### ISSUE TITLE
Error using with irb: undefined method `start' for Boson:Module

### ISSUE THREAD

**Issue by mattscilipoti** [cldwalker/boson#49]
I am following the instructions for [enhancing my irb](http://tagaholic.me/2009/10/19/how-boson-enhances-your-irb-experience.html).  I created an ~/.irbrc with:

```
require 'boson'
Boson.start
```

When I start irb, I receive this error:
`Error : 'load /Users/matt/.irbrc' : undefined method`start' for Boson:Module`

Those are the only two lines in my ~/.irbrc.  

I am investigating, but I was hoping you might have some guesses/insights.

**Comment by mattscilipoti** [comment]
I see that https://github.com/cldwalker/irbfiles is using `require 'boson/console'`.  That is working for me.

**Comment by cldwalker** [comment]
boson has undergone a major version since then. You'll need to install boson-more. The require is correct. This is described in boson-more's readme, https://github.com/cldwalker/boson-more#usage
