### ISSUE TITLE
Can't mix order of global and local flags

### ISSUE THREAD

**Issue by michaelbarton** [cldwalker/boson#5]
I've been trying to write my own boson command but I've been having some problems mixing the local and global flags to my query command. For example where -j is local flag and -f is the global fields flag:

```
> boson query genome -j bioinformatics -f=P
Deleted invalid option '-f=P'
```

Doesn't work because the global 'fields' option comes after the local journal option. If I reverse these two flags I can now specify which fields to view.

```
> boson query genome -f=P -j bioinformatics
```

Is this intentional? If possible I would like to be able to mix the order of local and global flags.

**Comment by cldwalker** [comment]
Hi Michael,
  It' on purpose: http://tagaholic.me/boson/doc/classes/Boson/OptionCommand.html
As the docs explain you can get put global options after local options as long as you separate them with '-'

> boson query genome -j bioinformatics - -f=P

I have mixed feelings about mixing them. Aside from it being technically harder to do, separating global from local becomes more important the more you use boson. I currently have 25 global options (and growing) and keeping them separated helps from mistakingly triggering a global when I mean a local (or vice versa).

Looking at your irbfiles, I noticed your require statements. If you want boson to detect gems that monkeypatch Object and Kernel methods and convert those to commands, then consider wrapping them in a self.included callback (i.e. http://github.com/cldwalker/irbfiles/blob/master/boson/commands/public/links.rb#L3-6).

Having been an undergrad physicist, I'll be interested to see what bioinfo-related boson commands you'll be making. :)

**Comment by michaelbarton** [comment]
Thanks for your reply I can understand about the problems about mixing the two types of flags. I still seem to have a similar problem using '-' though. Most likely it's a bug in my code though because I'm still learning to write for boson.

```
boson query genome -j=bioinformatics - -f=P
Deleted invalid option '-'
Deleted invalid option '-f=P'
```

**Comment by michaelbarton** [comment]
Thanks for the suggestion about using self.included. When you wrote about monkey patching object and kernel were you referring to the 'open' method which is part of open-uri?

As for bioinformatics. I seem to start endless open source applications but never get round to finishing them. Using boson to query pubmed might actually be a piece of code that I'll use regularly and so hopefully I'll get round to get keeping it maintained and working.

**Comment by cldwalker** [comment]
Ah, you'll need the latest boson, 0.2.2 for the '-' to work.

Methods like 'open' are ones that boson detects and lists as commands. This may not always be desired behavior (in the case of rails which adds 70+ monkeypatched methods). But for such rare cases, you can disable detection setting :object_methods to false in your library's configuration: http://tagaholic.me/boson/doc/classes/Boson/Library.html#M000105

**Comment by michaelbarton** [comment]
Ok, thanks. That fixed it. Updating to 0.2.2 allowed me to use '-' to separate global and local flags.

**Comment by cldwalker** [comment]
Glad it worked out
