### ISSUE TITLE
Minor ruby 2.1 change breaks boson

### ISSUE THREAD

**Issue by zhando** [cldwalker/boson#51]
Module#define_method returns a symbol in ruby 2.1. Boson expects a proc..

https://gist.github.com/zhando/7149837

This issue is just a heads up. I'll be submitting a pull request shortly that should work from ruby 1.9.2 and up.

**Comment by cldwalker** [comment]
Thanks for reporting your issue! This is [one of my 14 active issues](https://gh-active-issues.herokuapp.com/#cldwalker/boson#51). Use that link to check how soon your issue will be answered. Don't forget to check your issue against this project's CONTRIBUTING.md. Cheers.

**Comment by cldwalker** [comment]
Merged and released. Thanks!
