### ISSUE TITLE
Is this gem abandoned?

### ISSUE THREAD

**Issue by nengxu** [cldwalker/boson#54]
Hi, I first heard Boson after I had written Dolphin:

https://github.com/nengxu/dolphin

Then I thought that I may rewrite Dolphin using Boson.

The last commit of Boson was almost one year ago. Could you please confirm if this gem has been abandoned? If so, it would be a pity. Thanks.

**Comment by cldwalker** [comment]
Thanks for reporting your issue! This is [one of my 15 active issues](https://gh-active-issues.herokuapp.com/#cldwalker/boson#54). Use that link to check how soon your issue will be answered. Don't forget to check your issue against this project's CONTRIBUTING.md. Cheers.

**Comment by cldwalker** [comment]
No abandonment confirmed ;) Recent commits isn't necessarily an indicator of abandonment. I'm not actively developing it as I'm happy with where it is

**Comment by nengxu** [comment]
Thanks for your quick response. It is good to know that you are happy with its status quo. On a side note, it would be good to know if Boson is used by some other projects / gems.
