### ISSUE TITLE
Proc around command call

### ISSUE THREAD

**Issue by martinos** [cldwalker/boson#8]
It would be interesting to have the ability to give a proc that would wrap the actual command call. This way it would be easier had a custom error handling (eg. sending email on exception). Or on long running command, to send an email on command completion, or simply logging all command calls with their attributes.

**Comment by cldwalker** [comment]
I agree that would be useful. Boson commands can be wrapped by Boson::Scientist.commandify or when enabled as an option_command but the wrapping doesn't allow a custom proc. I may eventually implement something like this to wrap commands for benchmarking or debugging command wrappers.  In the meantime, feel free to fork.

**Comment by cldwalker** [comment]
Seeing this has been around for awhile and boson 1.0 is out, I'd encourage you to make this a plugin if you're still interested. Closing.
