### ISSUE TITLE
Can't find a place to put personal Hirb view.

### ISSUE THREAD

**Issue by martinos** [cldwalker/boson#9]
Where should I put personal Hirb views ?

I don't want to put them in the .irbrc file since I want to use the view at the bash level.

**Comment by cldwalker** [comment]
You should make any files you want to load at the bash level default libraries. A default library is a library (under ~/.boson/commands) that has been configured to load under the :defaults config key i.e. http://github.com/cldwalker/irbfiles/blob/88740d964b842e512c2ee4d9eea6ad7574aaea4a/boson/config/boson.yml#L2-3

You should also make sure that classes you want to keep at the top level are prefixed with '::'. For example see ::TwoDMenu in http://github.com/cldwalker/irbfiles/blob/master/boson/commands/public/plugins/menu_pipe.rb

**Comment by martinos** [comment]
Thanks, I tried it and it works like a charm.

**Comment by cldwalker** [comment]
Awesome :)
